# Setup
title:               Franziska Pellegrini
tagline:             'Researcher at Charité Berlin'
description:         ''
url:                 https://fpellegrini.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Franziska Pellegrini
  url:               https://twitter.com/pellegrini_fp
  email:             franziska.pellegrini@charite.de

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
